workflows:
  ios-release:
    name: iOS Release
    integrations:
      app_store_connect: Codemagic
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mertkoc.paintogain
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
